### PR TITLE
added zuul support

### PR DESCRIPTION
**Pull request by fredericlepied**

### CODE REVIEW

**Comment by rgarrigue** [comment]
recheck

**Comment by pc-m** [comment]
recheck

**Comment by fblackburn1** [comment]
FYI repo is not in https://github.com/TinxHQ/wazo-production-sf-config/blob/master/resources/resources.yaml

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
Need to bump changelog
```
dahdi-dbgsym_3.0.0-1~wazo1_amd64.deb not greater than repository version (12:3.0.0-1~wazo1.deb10)
```
But I don't know impact to do it

**Comment by fblackburn1** [comment]
> Need to bump changelog
> 
> ```
> dahdi-dbgsym_3.0.0-1~wazo1_amd64.deb not greater than repository version (12:3.0.0-1~wazo1.deb10)
> ```
> 
> But I don't know impact to do it

@pc-m @sduthil do you have objection/hints to bump version to merge this PR?

**Comment by pc-m** [comment]
> > Need to bump changelog
> > ```
> > dahdi-dbgsym_3.0.0-1~wazo1_amd64.deb not greater than repository version (12:3.0.0-1~wazo1.deb10)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But I don't know impact to do it
> 
> @pc-m @sduthil do you have objection/hints to bump version to merge this PR?

No objection

**Comment by sduthil** [comment]
No objections either

**Review by fblackburn1 — DISMISSED** [review]

**Review by fblackburn1 — APPROVED** [review]

**Pull request merged**
